replicaCount: 1
image: <+artifact.image>
service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: harness-java-demo.local
  path: /
  pathType: Prefix

resources: {}
